OCCUPATIONS = {
      0L: {'name': 'National Average',
        'occupations': [{'id': '00-0000',
                        'name': 'National Average of all Occupations'}],
        },
      11L: {'name': 'Management',
       'occupations': [{'id': '11-3011',
                        'name': 'Administrative Services Managers'},
                       {'id': '11-2011',
                        'name': 'Advertising and Promotions Managers'},
                       {'id': '11-9041',
                        'name': 'Architectural and Engineering Managers'},
                       {'id': '11-1011', 'name': 'Chief Executives'},
                       {'id': '11-3111',
                        'name': 'Compensation and Benefits Managers'},
                       {'id': '11-3021',
                        'name': 'Computer and Information Systems Managers'},
                       {'id': '11-9021', 'name': 'Construction Managers'},
                       {'id': '11-9039',
                        'name': 'Education Administrators, All Other'},
                       {'id': '11-9032',
                        'name': 'Education Administrators, Elementary and Secondary School'},
                       {'id': '11-9033',
                        'name': 'Education Administrators, Postsecondary'},
                       {'id': '11-9031',
                        'name': 'Education Administrators, Preschool and Childcare Center/Program'},
                       {'id': '11-9161',
                        'name': 'Emergency Management Directors'},
                       {'id': '11-9013',
                        'name': 'Farmers, Ranchers, and Other Agricultural Managers'},
                       {'id': '11-3031', 'name': 'Financial Managers'},
                       {'id': '11-9051', 'name': 'Food Service Managers'},
                       {'id': '11-9071', 'name': 'Gaming Managers'},
                       {'id': '11-1021',
                        'name': 'General and Operations Managers'},
                       {'id': '11-3121', 'name': 'Human Resources Managers'},
                       {'id': '11-3051',
                        'name': 'Industrial Production Managers'},
                       {'id': '11-1031', 'name': 'Legislators'},
                       {'id': '11-9081', 'name': 'Lodging Managers'},
                       {'id': '11-9199', 'name': 'Managers, All Other'},
                       {'id': '11-2021', 'name': 'Marketing Managers'},
                       {'id': '11-9111',
                        'name': 'Medical and Health Services Managers'},
                       {'id': '11-9121',
                        'name': 'Natural Sciences Managers'},
                       {'id': '11-9131',
                        'name': 'Postmasters and Mail Superintendents'},
                       {'id': '11-9141',
                        'name': 'Property, Real Estate, and Community Association Managers'},
                       {'id': '11-2031',
                        'name': 'Public Relations and Fundraising Managers'},
                       {'id': '11-3061', 'name': 'Purchasing Managers'},
                       {'id': '11-2022', 'name': 'Sales Managers'},
                       {'id': '11-9151',
                        'name': 'Social and Community Service Managers'},
                       {'id': '11-3131',
                        'name': 'Training and Development Managers'},
                       {'id': '11-3071',
                        'name': 'Transportation, Storage, and Distribution Managers'}]},
 13L: {'name': 'Business and Financial Operations',
       'occupations': [{'id': '13-2011', 'name': 'Accountants and Auditors'},
                       {'id': '13-1011',
                        'name': 'Agents and Business Managers of Artists, Performers, and Athletes'},
                       {'id': '13-2021',
                        'name': 'Appraisers and Assessors of Real Estate'},
                       {'id': '13-2031', 'name': 'Budget Analysts'},
                       {'id': '13-1199',
                        'name': 'Business Operations Specialists, All Other*'},
                       {'id': '13-1021',
                        'name': 'Buyers and Purchasing Agents, Farm Products'},
                       {'id': '13-1031',
                        'name': 'Claims Adjusters, Examiners, and Investigators'},
                       {'id': '13-1141',
                        'name': 'Compensation, Benefits, and Job Analysis Specialists'},
                       {'id': '13-1041', 'name': 'Compliance Officers'},
                       {'id': '13-1051', 'name': 'Cost Estimators'},
                       {'id': '13-2041', 'name': 'Credit Analysts'},
                       {'id': '13-2071', 'name': 'Credit Counselors'},
                       {'id': '13-1074', 'name': 'Farm Labor Contractors'},
                       {'id': '13-2051', 'name': 'Financial Analysts'},
                       {'id': '13-2061', 'name': 'Financial Examiners'},
                       {'id': '13-2099',
                        'name': 'Financial Specialists, All Other'},
                       {'id': '13-1078',
                        'name': 'Human Resources, Training, and Labor Relations Specialists, All Other*'},
                       {'id': '13-1032',
                        'name': 'Insurance Appraisers, Auto Damage'},
                       {'id': '13-2053', 'name': 'Insurance Underwriters'},
                       {'id': '13-2072', 'name': 'Loan Officers'},
                       {'id': '13-1081', 'name': 'Logisticians'},
                       {'id': '13-1111', 'name': 'Management Analysts'},
                       {'id': '13-1161',
                        'name': 'Market Research Analysts and Marketing Specialists*'},
                       {'id': '13-1121',
                        'name': 'Meeting, Convention, and Event Planners*'},
                       {'id': '13-2052',
                        'name': 'Personal Financial Advisors'},
                       {'id': '13-1023',
                        'name': 'Purchasing Agents, Except Wholesale, Retail, and Farm Products'},
                       {'id': '13-2081',
                        'name': 'Tax Examiners and Collectors, and Revenue Agents'},
                       {'id': '13-2082', 'name': 'Tax Preparers'},
                       {'id': '13-1151',
                        'name': 'Training and Development Specialists'},
                       {'id': '13-1022',
                        'name': 'Wholesale and Retail Buyers, Except Farm Products'}]},
 15L: {'name': 'Computer and Mathematical',
       'occupations': [{'id': '15-2011', 'name': 'Actuaries'},
                       {'id': '15-1111',
                        'name': 'Computer and Information Research Scientists'},
                       {'id': '15-1799',
                        'name': 'Computer Occupations, All Other*'},
                       {'id': '15-1131', 'name': 'Computer Programmers'},
                       {'id': '15-1150',
                        'name': 'Computer Support Specialists'},
                       {'id': '15-1121',
                        'name': 'Computer Systems Analysts'},
                       {'id': '15-1141', 'name': 'Database Administrators'},
                       {'id': '15-1179',
                        'name': 'Information Security Analysts, Web Developers, and Computer Network Architects'},
                       {'id': '15-2099',
                        'name': 'Mathematical Science Occupations, All Other'},
                       {'id': '15-2091', 'name': 'Mathematical Technicians'},
                       {'id': '15-2021', 'name': 'Mathematicians'},
                       {'id': '15-1142',
                        'name': 'Network and Computer Systems Administrators*'},
                       {'id': '15-2031',
                        'name': 'Operations Research Analysts'},
                       {'id': '15-1132',
                        'name': 'Software Developers, Applications'},
                       {'id': '15-1133',
                        'name': 'Software Developers, Systems Software'},
                       {'id': '15-2041', 'name': 'Statisticians'}]},
 17L: {'name': 'Architecture and Engineering',
       'occupations': [{'id': '17-3021',
                        'name': 'Aerospace Engineering and Operations Technicians'},
                       {'id': '17-2011', 'name': 'Aerospace Engineers'},
                       {'id': '17-2021', 'name': 'Agricultural Engineers'},
                       {'id': '17-1011',
                        'name': 'Architects, Except Landscape and Naval'},
                       {'id': '17-3011',
                        'name': 'Architectural and Civil Drafters'},
                       {'id': '17-2031', 'name': 'Biomedical Engineers'},
                       {'id': '17-1021',
                        'name': 'Cartographers and Photogrammetrists'},
                       {'id': '17-2041', 'name': 'Chemical Engineers'},
                       {'id': '17-3022',
                        'name': 'Civil Engineering Technicians'},
                       {'id': '17-2051', 'name': 'Civil Engineers'},
                       {'id': '17-2061',
                        'name': 'Computer Hardware Engineers'},
                       {'id': '17-3019', 'name': 'Drafters, All Other'},
                       {'id': '17-3012',
                        'name': 'Electrical and Electronics Drafters'},
                       {'id': '17-3023',
                        'name': 'Electrical and Electronics Engineering Technicians'},
                       {'id': '17-2071', 'name': 'Electrical Engineers'},
                       {'id': '17-3024',
                        'name': 'Electro-Mechanical Technicians'},
                       {'id': '17-2072',
                        'name': 'Electronics Engineers, Except Computer'},
                       {'id': '17-3029',
                        'name': 'Engineering Technicians, Except Drafters, All Other'},
                       {'id': '17-2199', 'name': 'Engineers, All Other'},
                       {'id': '17-3025',
                        'name': 'Environmental Engineering Technicians'},
                       {'id': '17-2081', 'name': 'Environmental Engineers'},
                       {'id': '17-2111',
                        'name': 'Health and Safety Engineers, Except Mining Safety Engineers and Inspectors'},
                       {'id': '17-3026',
                        'name': 'Industrial Engineering Technicians'},
                       {'id': '17-2112', 'name': 'Industrial Engineers'},
                       {'id': '17-1012', 'name': 'Landscape Architects'},
                       {'id': '17-2121',
                        'name': 'Marine Engineers and Naval Architects'},
                       {'id': '17-2131', 'name': 'Materials Engineers'},
                       {'id': '17-3013', 'name': 'Mechanical Drafters'},
                       {'id': '17-3027',
                        'name': 'Mechanical Engineering Technicians'},
                       {'id': '17-2141', 'name': 'Mechanical Engineers'},
                       {'id': '17-2151',
                        'name': 'Mining and Geological Engineers, Including Mining Safety Engineers'},
                       {'id': '17-2161', 'name': 'Nuclear Engineers'},
                       {'id': '17-2171', 'name': 'Petroleum Engineers'},
                       {'id': '17-3031',
                        'name': 'Surveying and Mapping Technicians'},
                       {'id': '17-1022', 'name': 'Surveyors'}]},
 19L: {'name': 'Life, Physical, and Social Science',
       'occupations': [{'id': '19-4011',
                        'name': 'Agricultural and Food Science Technicians'},
                       {'id': '19-1011', 'name': 'Animal Scientists'},
                       {'id': '19-3091',
                        'name': 'Anthropologists and Archeologists'},
                       {'id': '19-2011', 'name': 'Astronomers'},
                       {'id': '19-2021',
                        'name': 'Atmospheric and Space Scientists'},
                       {'id': '19-1021',
                        'name': 'Biochemists and Biophysicists'},
                       {'id': '19-1029',
                        'name': 'Biological Scientists, All Other'},
                       {'id': '19-4021', 'name': 'Biological Technicians'},
                       {'id': '19-4031', 'name': 'Chemical Technicians'},
                       {'id': '19-2031', 'name': 'Chemists'},
                       {'id': '19-3031',
                        'name': 'Clinical, Counseling, and School Psychologists'},
                       {'id': '19-1031', 'name': 'Conservation Scientists'},
                       {'id': '19-3011', 'name': 'Economists'},
                       {'id': '19-4091',
                        'name': 'Environmental Science and Protection Technicians, Including Health'},
                       {'id': '19-2041',
                        'name': 'Environmental Scientists and Specialists, Including Health'},
                       {'id': '19-1041', 'name': 'Epidemiologists'},
                       {'id': '19-1012',
                        'name': 'Food Scientists and Technologists'},
                       {'id': '19-4092',
                        'name': 'Forensic Science Technicians'},
                       {'id': '19-4093',
                        'name': 'Forest and Conservation Technicians'},
                       {'id': '19-1032', 'name': 'Foresters'},
                       {'id': '19-3092', 'name': 'Geographers'},
                       {'id': '19-4041',
                        'name': 'Geological and Petroleum Technicians'},
                       {'id': '19-2042',
                        'name': 'Geoscientists, Except Hydrologists and Geographers'},
                       {'id': '19-3093', 'name': 'Historians'},
                       {'id': '19-2043', 'name': 'Hydrologists'},
                       {'id': '19-3032',
                        'name': 'Industrial-Organizational Psychologists'},
                       {'id': '19-1099',
                        'name': 'Life Scientists, All Other'},
                       {'id': '19-4099',
                        'name': 'Life, Physical, and Social Science Technicians, All Other'},
                       {'id': '19-2032', 'name': 'Materials Scientists'},
                       {'id': '19-1042',
                        'name': 'Medical Scientists, Except Epidemiologists'},
                       {'id': '19-1022', 'name': 'Microbiologists'},
                       {'id': '19-4051', 'name': 'Nuclear Technicians'},
                       {'id': '19-2099',
                        'name': 'Physical Scientists, All Other'},
                       {'id': '19-2012', 'name': 'Physicists'},
                       {'id': '19-3094', 'name': 'Political Scientists'},
                       {'id': '19-3039', 'name': 'Psychologists, All Other'},
                       {'id': '19-4061',
                        'name': 'Social Science Research Assistants'},
                       {'id': '19-3099',
                        'name': 'Social Scientists and Related Workers, All Other'},
                       {'id': '19-3041', 'name': 'Sociologists'},
                       {'id': '19-1013',
                        'name': 'Soil and Plant Scientists'},
                       {'id': '19-3022', 'name': 'Survey Researchers'},
                       {'id': '19-3051',
                        'name': 'Urban and Regional Planners'},
                       {'id': '19-1023',
                        'name': 'Zoologists and Wildlife Biologists'}]},
 21L: {'name': 'Community and Social Service',
       'occupations': [{'id': '21-1021',
                        'name': 'Child, Family, and School Social Workers'},
                       {'id': '21-2011', 'name': 'Clergy'},
                       {'id': '21-1798',
                        'name': 'Community and Social Service Specialists, All Other*'},
                       {'id': '21-1019', 'name': 'Counselors, All Other'},
                       {'id': '21-2021',
                        'name': 'Directors, Religious Activities and Education'},
                       {'id': '21-1012',
                        'name': 'Educational, Guidance, School, and Vocational Counselors'},
                       {'id': '21-1091', 'name': 'Health Educators'},
                       {'id': '21-1022',
                        'name': 'Healthcare Social Workers'},
                       {'id': '21-1013',
                        'name': 'Marriage and Family Therapists'},
                       {'id': '21-1023',
                        'name': 'Mental Health and Substance Abuse Social Workers'},
                       {'id': '21-1014', 'name': 'Mental Health Counselors'},
                       {'id': '21-1092',
                        'name': 'Probation Officers and Correctional Treatment Specialists'},
                       {'id': '21-1015',
                        'name': 'Rehabilitation Counselors'},
                       {'id': '21-2099',
                        'name': 'Religious Workers, All Other'},
                       {'id': '21-1093',
                        'name': 'Social and Human Service Assistants'},
                       {'id': '21-1029',
                        'name': 'Social Workers, All Other'},
                       {'id': '21-1011',
                        'name': 'Substance Abuse and Behavioral Disorder Counselors'}]},
 23L: {'name': 'Legal',
       'occupations': [{'id': '23-1021',
                        'name': 'Administrative Law Judges, Adjudicators, and Hearing Officers'},
                       {'id': '23-1022',
                        'name': 'Arbitrators, Mediators, and Conciliators'},
                       {'id': '23-2091', 'name': 'Court Reporters'},
                       {'id': '23-1023',
                        'name': 'Judges, Magistrate Judges, and Magistrates'},
                       {'id': '23-1012', 'name': 'Judicial Law Clerks'},
                       {'id': '23-1011', 'name': 'Lawyers'},
                       {'id': '23-2099',
                        'name': 'Legal Support Workers, All Other'},
                       {'id': '23-2011',
                        'name': 'Paralegals and Legal Assistants*'},
                       {'id': '23-2093',
                        'name': 'Title Examiners, Abstractors, and Searchers'}]},
 25L: {'name': 'Education, Training, and Library',
       'occupations': [{'id': '25-3011',
                        'name': 'Adult Basic and Secondary Education and Literacy Teachers and Instructors'},
                       {'id': '25-1041',
                        'name': 'Agricultural Sciences Teachers, Postsecondary'},
                       {'id': '25-1061',
                        'name': 'Anthropology and Archeology Teachers, Postsecondary'},
                       {'id': '25-1031',
                        'name': 'Architecture Teachers, Postsecondary'},
                       {'id': '25-4011', 'name': 'Archivists'},
                       {'id': '25-1062',
                        'name': 'Area, Ethnic, and Cultural Studies Teachers, Postsecondary'},
                       {'id': '25-1121',
                        'name': 'Art, Drama, and Music Teachers, Postsecondary'},
                       {'id': '25-1051',
                        'name': 'Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary'},
                       {'id': '25-9011',
                        'name': 'Audio-Visual and Multimedia Collections Specialists'},
                       {'id': '25-1042',
                        'name': 'Biological Science Teachers, Postsecondary'},
                       {'id': '25-1011',
                        'name': 'Business Teachers, Postsecondary'},
                       {'id': '25-2023',
                        'name': 'Career/Technical Education Teachers, Middle School'},
                       {'id': '25-2032',
                        'name': 'Career/Technical Education Teachers, Secondary School'},
                       {'id': '25-1052',
                        'name': 'Chemistry Teachers, Postsecondary'},
                       {'id': '25-1122',
                        'name': 'Communications Teachers, Postsecondary'},
                       {'id': '25-1021',
                        'name': 'Computer Science Teachers, Postsecondary'},
                       {'id': '25-1111',
                        'name': 'Criminal Justice and Law Enforcement Teachers, Postsecondary'},
                       {'id': '25-4012', 'name': 'Curators'},
                       {'id': '25-1063',
                        'name': 'Economics Teachers, Postsecondary'},
                       {'id': '25-1081',
                        'name': 'Education Teachers, Postsecondary'},
                       {'id': '25-9099',
                        'name': 'Education, Training, and Library Workers, All Other'},
                       {'id': '25-2021',
                        'name': 'Elementary School Teachers, Except Special Education'},
                       {'id': '25-1032',
                        'name': 'Engineering Teachers, Postsecondary'},
                       {'id': '25-1123',
                        'name': 'English Language and Literature Teachers, Postsecondary'},
                       {'id': '25-1053',
                        'name': 'Environmental Science Teachers, Postsecondary'},
                       {'id': '25-9021',
                        'name': 'Farm and Home Management Advisors'},
                       {'id': '25-1124',
                        'name': 'Foreign Language and Literature Teachers, Postsecondary'},
                       {'id': '25-1043',
                        'name': 'Forestry and Conservation Science Teachers, Postsecondary'},
                       {'id': '25-1064',
                        'name': 'Geography Teachers, Postsecondary'},
                       {'id': '25-1191',
                        'name': 'Graduate Teaching Assistants'},
                       {'id': '25-1071',
                        'name': 'Health Specialties Teachers, Postsecondary'},
                       {'id': '25-1125',
                        'name': 'History Teachers, Postsecondary'},
                       {'id': '25-1192',
                        'name': 'Home Economics Teachers, Postsecondary'},
                       {'id': '25-9031',
                        'name': 'Instructional Coordinators'},
                       {'id': '25-2012',
                        'name': 'Kindergarten Teachers, Except Special Education'},
                       {'id': '25-1112',
                        'name': 'Law Teachers, Postsecondary'},
                       {'id': '25-4021', 'name': 'Librarians'},
                       {'id': '25-1082',
                        'name': 'Library Science Teachers, Postsecondary'},
                       {'id': '25-4031', 'name': 'Library Technicians'},
                       {'id': '25-1022',
                        'name': 'Mathematical Science Teachers, Postsecondary'},
                       {'id': '25-2022',
                        'name': 'Middle School Teachers, Except Special and Career/Technical Education'},
                       {'id': '25-4013',
                        'name': 'Museum Technicians and Conservators'},
                       {'id': '25-1072',
                        'name': 'Nursing Instructors and Teachers, Postsecondary'},
                       {'id': '25-1126',
                        'name': 'Philosophy and Religion Teachers, Postsecondary'},
                       {'id': '25-1054',
                        'name': 'Physics Teachers, Postsecondary'},
                       {'id': '25-1065',
                        'name': 'Political Science Teachers, Postsecondary'},
                       {'id': '25-1199',
                        'name': 'Postsecondary Teachers, All Other'},
                       {'id': '25-2011',
                        'name': 'Preschool Teachers, Except Special Education'},
                       {'id': '25-1066',
                        'name': 'Psychology Teachers, Postsecondary'},
                       {'id': '25-1193',
                        'name': 'Recreation and Fitness Studies Teachers, Postsecondary'},
                       {'id': '25-2031',
                        'name': 'Secondary School Teachers, Except Special and Career/Technical Education'},
                       {'id': '25-3021',
                        'name': 'Self-Enrichment Education Teachers'},
                       {'id': '25-1069',
                        'name': 'Social Sciences Teachers, Postsecondary, All Other'},
                       {'id': '25-1113',
                        'name': 'Social Work Teachers, Postsecondary'},
                       {'id': '25-1067',
                        'name': 'Sociology Teachers, Postsecondary'},
                       {'id': '25-2053',
                        'name': 'Special Education Teachers, Middle School'},
                       {'id': '25-2041',
                        'name': 'Special Education Teachers, Preschool, Kindergarten, and Elementary School*'},
                       {'id': '25-2054',
                        'name': 'Special Education Teachers, Secondary School'},
                       {'id': '25-9041', 'name': 'Teacher Assistants'},
                       {'id': '25-3999',
                        'name': 'Teachers and Instructors, All Other*'},
                       {'id': '25-1194',
                        'name': 'Vocational Education Teachers, Postsecondary'}]},
 27L: {'name': 'Arts, Design, Entertainment, Sports, and Media',
       'occupations': [{'id': '27-2011', 'name': 'Actors'},
                       {'id': '27-1011', 'name': 'Art Directors'},
                       {'id': '27-1019',
                        'name': 'Artists and Related Workers, All Other'},
                       {'id': '27-2021',
                        'name': 'Athletes and Sports Competitors'},
                       {'id': '27-4011',
                        'name': 'Audio and Video Equipment Technicians'},
                       {'id': '27-3021', 'name': 'Broadcast News Analysts'},
                       {'id': '27-4012', 'name': 'Broadcast Technicians'},
                       {'id': '27-4031',
                        'name': 'Camera Operators, Television, Video, and Motion Picture'},
                       {'id': '27-2032', 'name': 'Choreographers'},
                       {'id': '27-2022', 'name': 'Coaches and Scouts'},
                       {'id': '27-1021',
                        'name': 'Commercial and Industrial Designers'},
                       {'id': '27-1012', 'name': 'Craft Artists'},
                       {'id': '27-2031', 'name': 'Dancers'},
                       {'id': '27-1029', 'name': 'Designers, All Other'},
                       {'id': '27-3041', 'name': 'Editors'},
                       {'id': '27-2099',
                        'name': 'Entertainers and Performers, Sports and Related Workers, All Other'},
                       {'id': '27-1022', 'name': 'Fashion Designers'},
                       {'id': '27-4032', 'name': 'Film and Video Editors'},
                       {'id': '27-1013',
                        'name': 'Fine Artists, Including Painters, Sculptors, and Illustrators'},
                       {'id': '27-1023', 'name': 'Floral Designers'},
                       {'id': '27-1024', 'name': 'Graphic Designers'},
                       {'id': '27-1025', 'name': 'Interior Designers'},
                       {'id': '27-3091',
                        'name': 'Interpreters and Translators'},
                       {'id': '27-4099',
                        'name': 'Media and Communication Equipment Workers, All Other'},
                       {'id': '27-3099',
                        'name': 'Media and Communication Workers, All Other'},
                       {'id': '27-1026',
                        'name': 'Merchandise Displayers and Window Trimmers'},
                       {'id': '27-1014',
                        'name': 'Multimedia Artists and Animators'},
                       {'id': '27-2041',
                        'name': 'Music Directors and Composers'},
                       {'id': '27-2042', 'name': 'Musicians and Singers'},
                       {'id': '27-4021', 'name': 'Photographers'},
                       {'id': '27-2012', 'name': 'Producers and Directors'},
                       {'id': '27-3012',
                        'name': 'Public Address System and Other Announcers'},
                       {'id': '27-3031',
                        'name': 'Public Relations Specialists'},
                       {'id': '27-3011',
                        'name': 'Radio and Television Announcers'},
                       {'id': '27-4013', 'name': 'Radio Operators'},
                       {'id': '27-3022',
                        'name': 'Reporters and Correspondents'},
                       {'id': '27-1027',
                        'name': 'Set and Exhibit Designers'},
                       {'id': '27-4014',
                        'name': 'Sound Engineering Technicians'},
                       {'id': '27-3042', 'name': 'Technical Writers'},
                       {'id': '27-2023',
                        'name': 'Umpires, Referees, and Other Sports Officials'},
                       {'id': '27-3043', 'name': 'Writers and Authors'}]},
 29L: {'name': 'Healthcare Practitioners and Technical',
       'occupations': [{'id': '29-1061', 'name': 'Anesthesiologists'},
                       {'id': '29-9091', 'name': 'Athletic Trainers'},
                       {'id': '29-1181', 'name': 'Audiologists'},
                       {'id': '29-2031',
                        'name': 'Cardiovascular Technologists and Technicians'},
                       {'id': '29-1011', 'name': 'Chiropractors'},
                       {'id': '29-2021', 'name': 'Dental Hygienists'},
                       {'id': '29-1029',
                        'name': 'Dentists, All Other Specialists'},
                       {'id': '29-1021', 'name': 'Dentists, General'},
                       {'id': '29-2032',
                        'name': 'Diagnostic Medical Sonographers'},
                       {'id': '29-2051', 'name': 'Dietetic Technicians'},
                       {'id': '29-1031',
                        'name': 'Dietitians and Nutritionists'},
                       {'id': '29-2041',
                        'name': 'Emergency Medical Technicians and Paramedics'},
                       {'id': '29-1062',
                        'name': 'Family and General Practitioners'},
                       {'id': '29-1199',
                        'name': 'Health Diagnosing and Treating Practitioners, All Other'},
                       {'id': '29-2799',
                        'name': 'Health Technologists and Technicians, All Other*'},
                       {'id': '29-9799',
                        'name': 'Healthcare Practitioners and Technical Workers, All Other*'},
                       {'id': '29-1063', 'name': 'Internists, General'},
                       {'id': '29-2061',
                        'name': 'Licensed Practical and Licensed Vocational Nurses'},
                       {'id': '29-2012',
                        'name': 'Medical and Clinical Laboratory Technicians'},
                       {'id': '29-2011',
                        'name': 'Medical and Clinical Laboratory Technologists'},
                       {'id': '29-2071',
                        'name': 'Medical Records and Health Information Technicians'},
                       {'id': '29-2033',
                        'name': 'Nuclear Medicine Technologists'},
                       {'id': '29-1064',
                        'name': 'Obstetricians and Gynecologists'},
                       {'id': '29-9011',
                        'name': 'Occupational Health and Safety Specialists'},
                       {'id': '29-9012',
                        'name': 'Occupational Health and Safety Technicians'},
                       {'id': '29-1122', 'name': 'Occupational Therapists'},
                       {'id': '29-2081', 'name': 'Opticians, Dispensing'},
                       {'id': '29-1041', 'name': 'Optometrists'},
                       {'id': '29-1022',
                        'name': 'Oral and Maxillofacial Surgeons'},
                       {'id': '29-1023', 'name': 'Orthodontists'},
                       {'id': '29-2091',
                        'name': 'Orthotists and Prosthetists'},
                       {'id': '29-1065', 'name': 'Pediatricians, General'},
                       {'id': '29-1051', 'name': 'Pharmacists'},
                       {'id': '29-2052', 'name': 'Pharmacy Technicians'},
                       {'id': '29-1123', 'name': 'Physical Therapists'},
                       {'id': '29-1071', 'name': 'Physician Assistants'},
                       {'id': '29-1069',
                        'name': 'Physicians and Surgeons, All Other'},
                       {'id': '29-1081', 'name': 'Podiatrists'},
                       {'id': '29-2053', 'name': 'Psychiatric Technicians'},
                       {'id': '29-1066', 'name': 'Psychiatrists'},
                       {'id': '29-1124', 'name': 'Radiation Therapists'},
                       {'id': '29-2037',
                        'name': 'Radiologic Technologists and Technicians*'},
                       {'id': '29-1125', 'name': 'Recreational Therapists'},
                       {'id': '29-1111', 'name': 'Registered Nurses*'},
                       {'id': '29-1126', 'name': 'Respiratory Therapists'},
                       {'id': '29-2054',
                        'name': 'Respiratory Therapy Technicians'},
                       {'id': '29-1127',
                        'name': 'Speech-Language Pathologists'},
                       {'id': '29-1067', 'name': 'Surgeons'},
                       {'id': '29-2055', 'name': 'Surgical Technologists'},
                       {'id': '29-1128', 'name': 'Therapists, All Other*'},
                       {'id': '29-1131', 'name': 'Veterinarians'},
                       {'id': '29-2056',
                        'name': 'Veterinary Technologists and Technicians'}]},
 31L: {'name': 'Healthcare Support',
       'occupations': [{'id': '31-9091', 'name': 'Dental Assistants'},
                       {'id': '31-9799',
                        'name': 'Healthcare Support Workers, All Other*'},
                       {'id': '31-1011', 'name': 'Home Health Aides'},
                       {'id': '31-9011', 'name': 'Massage Therapists'},
                       {'id': '31-9092', 'name': 'Medical Assistants'},
                       {'id': '31-9093',
                        'name': 'Medical Equipment Preparers'},
                       {'id': '31-9094',
                        'name': 'Medical Transcriptionists'},
                       {'id': '31-1012',
                        'name': 'Nursing Aides, Orderlies, and Attendants*'},
                       {'id': '31-2012',
                        'name': 'Occupational Therapy Aides'},
                       {'id': '31-2011',
                        'name': 'Occupational Therapy Assistants'},
                       {'id': '31-9095', 'name': 'Pharmacy Aides'},
                       {'id': '31-2022', 'name': 'Physical Therapist Aides'},
                       {'id': '31-2021',
                        'name': 'Physical Therapist Assistants'},
                       {'id': '31-1013', 'name': 'Psychiatric Aides'},
                       {'id': '31-9096',
                        'name': 'Veterinary Assistants and Laboratory Animal Caretakers'}]},
 33L: {'name': 'Protective Service',
       'occupations': [{'id': '33-9011', 'name': 'Animal Control Workers'},
                       {'id': '33-3011', 'name': 'Bailiffs'},
                       {'id': '33-3012',
                        'name': 'Correctional Officers and Jailers'},
                       {'id': '33-9091', 'name': 'Crossing Guards'},
                       {'id': '33-3021',
                        'name': 'Detectives and Criminal Investigators'},
                       {'id': '33-2021',
                        'name': 'Fire Inspectors and Investigators'},
                       {'id': '33-2011', 'name': 'Firefighters'},
                       {'id': '33-1011',
                        'name': 'First-Line Supervisors of Correctional Officers'},
                       {'id': '33-1021',
                        'name': 'First-Line Supervisors of Fire Fighting and Prevention Workers'},
                       {'id': '33-1012',
                        'name': 'First-Line Supervisors of Police and Detectives'},
                       {'id': '33-1099',
                        'name': 'First-Line Supervisors of Protective Service Workers, All Other'},
                       {'id': '33-3031', 'name': 'Fish and Game Wardens'},
                       {'id': '33-9031',
                        'name': 'Gaming Surveillance Officers and Gaming Investigators'},
                       {'id': '33-9092',
                        'name': 'Lifeguards, Ski Patrol, and Other Recreational Protective Service Workers'},
                       {'id': '33-3041',
                        'name': 'Parking Enforcement Workers'},
                       {'id': '33-3051',
                        'name': "Police and Sheriff's Patrol Officers"},
                       {'id': '33-9021',
                        'name': 'Private Detectives and Investigators'},
                       {'id': '33-9099',
                        'name': 'Protective Service Workers, All Other *'},
                       {'id': '33-9032', 'name': 'Security Guards'},
                       {'id': '33-3052',
                        'name': 'Transit and Railroad Police'},
                       {'id': '33-9093',
                        'name': 'Transportation Security Screeners* (federal only)'}]},
 35L: {'name': 'Food Preparation and Serving Related',
       'occupations': [{'id': '35-3011', 'name': 'Bartenders'},
                       {'id': '35-1011', 'name': 'Chefs and Head Cooks'},
                       {'id': '35-3021',
                        'name': 'Combined Food Preparation and Serving Workers, Including Fast Food'},
                       {'id': '35-2019', 'name': 'Cooks, All Other'},
                       {'id': '35-2011', 'name': 'Cooks, Fast Food'},
                       {'id': '35-2012',
                        'name': 'Cooks, Institution and Cafeteria'},
                       {'id': '35-2014', 'name': 'Cooks, Restaurant'},
                       {'id': '35-2015', 'name': 'Cooks, Short Order'},
                       {'id': '35-3022',
                        'name': 'Counter Attendants, Cafeteria, Food Concession, and Coffee Shop'},
                       {'id': '35-9011',
                        'name': 'Dining Room and Cafeteria Attendants and Bartender Helpers'},
                       {'id': '35-9021', 'name': 'Dishwashers'},
                       {'id': '35-1012',
                        'name': 'First-Line Supervisors of Food Preparation and Serving Workers'},
                       {'id': '35-9099',
                        'name': 'Food Preparation and Serving Related Workers, All Other'},
                       {'id': '35-2021', 'name': 'Food Preparation Workers'},
                       {'id': '35-3041',
                        'name': 'Food Servers, Nonrestaurant'},
                       {'id': '35-9031',
                        'name': 'Hosts and Hostesses, Restaurant, Lounge, and Coffee Shop'},
                       {'id': '35-3031', 'name': 'Waiters and Waitresses'}]},
 37L: {'name': 'Building and Grounds Cleaning and Maintenance',
       'occupations': [{'id': '37-2019',
                        'name': 'Building Cleaning Workers, All Other'},
                       {'id': '37-1011',
                        'name': 'First-Line Supervisors of Housekeeping and Janitorial Workers'},
                       {'id': '37-1012',
                        'name': 'First-Line Supervisors of Landscaping, Lawn Service, and Groundskeeping Workers'},
                       {'id': '37-3019',
                        'name': 'Grounds Maintenance Workers, All Other'},
                       {'id': '37-2011',
                        'name': 'Janitors and Cleaners, Except Maids and Housekeeping Cleaners'},
                       {'id': '37-3011',
                        'name': 'Landscaping and Groundskeeping Workers'},
                       {'id': '37-2012',
                        'name': 'Maids and Housekeeping Cleaners'},
                       {'id': '37-2021', 'name': 'Pest Control Workers'},
                       {'id': '37-3012',
                        'name': 'Pesticide Handlers, Sprayers, and Applicators, Vegetation'},
                       {'id': '37-3013',
                        'name': 'Tree Trimmers and Pruners'}]},
 39L: {'name': 'Personal Care and Service',
       'occupations': [{'id': '39-3091',
                        'name': 'Amusement and Recreation Attendants'},
                       {'id': '39-2011', 'name': 'Animal Trainers'},
                       {'id': '39-6011',
                        'name': 'Baggage Porters and Bellhops'},
                       {'id': '39-5011', 'name': 'Barbers'},
                       {'id': '39-9011', 'name': 'Childcare Workers'},
                       {'id': '39-6012', 'name': 'Concierges'},
                       {'id': '39-3092', 'name': 'Costume Attendants'},
                       {'id': '39-4011', 'name': 'Embalmers'},
                       {'id': '39-3099',
                        'name': 'Entertainment Attendants and Related Workers, All Other'},
                       {'id': '39-1021',
                        'name': 'First-Line Supervisors of Personal Service Workers'},
                       {'id': '39-9031',
                        'name': 'Fitness Trainers and Aerobics Instructors'},
                       {'id': '39-4021', 'name': 'Funeral Attendants'},
                       {'id': '39-4831',
                        'name': 'Funeral Service Managers, Directors, Morticians, and Undertakers'},
                       {'id': '39-3012',
                        'name': 'Gaming and Sports Book Writers and Runners'},
                       {'id': '39-3011', 'name': 'Gaming Dealers'},
                       {'id': '39-3019',
                        'name': 'Gaming Service Workers, All Other'},
                       {'id': '39-1011', 'name': 'Gaming Supervisors'},
                       {'id': '39-5012',
                        'name': 'Hairdressers, Hairstylists, and Cosmetologists'},
                       {'id': '39-3093',
                        'name': 'Locker Room, Coatroom, and Dressing Room Attendants'},
                       {'id': '39-5091',
                        'name': 'Makeup Artists, Theatrical and Performance'},
                       {'id': '39-5092',
                        'name': 'Manicurists and Pedicurists'},
                       {'id': '39-3021',
                        'name': 'Motion Picture Projectionists'},
                       {'id': '39-2021',
                        'name': 'Nonfarm Animal Caretakers'},
                       {'id': '39-9021', 'name': 'Personal Care Aides'},
                       {'id': '39-9099',
                        'name': 'Personal Care and Service Workers, All Other'},
                       {'id': '39-9032', 'name': 'Recreation Workers'},
                       {'id': '39-9041', 'name': 'Residential Advisors'},
                       {'id': '39-5093', 'name': 'Shampooers'},
                       {'id': '39-5094', 'name': 'Skincare Specialists'},
                       {'id': '39-1012', 'name': 'Slot Supervisors'},
                       {'id': '39-7011', 'name': 'Tour Guides and Escorts'},
                       {'id': '39-7012', 'name': 'Travel Guides'},
                       {'id': '39-3031',
                        'name': 'Ushers, Lobby Attendants, and Ticket Takers'}]},
 41L: {'name': 'Sales and Related',
       'occupations': [{'id': '41-3011', 'name': 'Advertising Sales Agents'},
                       {'id': '41-2011', 'name': 'Cashiers'},
                       {'id': '41-2021',
                        'name': 'Counter and Rental Clerks'},
                       {'id': '41-9011',
                        'name': 'Demonstrators and Product Promoters'},
                       {'id': '41-9091',
                        'name': 'Door-to-Door Sales Workers, News and Street Vendors, and Related Workers'},
                       {'id': '41-1012',
                        'name': 'First-Line Supervisors of Non-Retail Sales Workers'},
                       {'id': '41-1011',
                        'name': 'First-Line Supervisors of Retail Sales Workers'},
                       {'id': '41-2012',
                        'name': 'Gaming Change Persons and Booth Cashiers'},
                       {'id': '41-3021', 'name': 'Insurance Sales Agents'},
                       {'id': '41-9012', 'name': 'Models'},
                       {'id': '41-2022', 'name': 'Parts Salespersons'},
                       {'id': '41-9021', 'name': 'Real Estate Brokers'},
                       {'id': '41-9022', 'name': 'Real Estate Sales Agents'},
                       {'id': '41-2031', 'name': 'Retail Salespersons'},
                       {'id': '41-9799',
                        'name': 'Sales and Related Workers, All Other*'},
                       {'id': '41-9031', 'name': 'Sales Engineers'},
                       {'id': '41-3099',
                        'name': 'Sales Representatives, Services, All Other'},
                       {'id': '41-4012',
                        'name': 'Sales Representatives, Wholesale and Manufacturing, Except Technical and Scientific Products'},
                       {'id': '41-4011',
                        'name': 'Sales Representatives, Wholesale and Manufacturing, Technical and Scientific Products'},
                       {'id': '41-3031',
                        'name': 'Securities, Commodities, and Financial Services Sales Agents'},
                       {'id': '41-9041', 'name': 'Telemarketers'},
                       {'id': '41-3041', 'name': 'Travel Agents'}]},
 43L: {'name': 'Office and Administrative Support',
       'occupations': [{'id': '43-3011',
                        'name': 'Bill and Account Collectors'},
                       {'id': '43-3021',
                        'name': 'Billing and Posting Clerks'},
                       {'id': '43-3031',
                        'name': 'Bookkeeping, Accounting, and Auditing Clerks'},
                       {'id': '43-4011', 'name': 'Brokerage Clerks'},
                       {'id': '43-5011', 'name': 'Cargo and Freight Agents'},
                       {'id': '43-2099',
                        'name': 'Communications Equipment Operators, All Other'},
                       {'id': '43-9011', 'name': 'Computer Operators'},
                       {'id': '43-4021', 'name': 'Correspondence Clerks'},
                       {'id': '43-5021', 'name': 'Couriers and Messengers'},
                       {'id': '43-4031',
                        'name': 'Court, Municipal, and License Clerks'},
                       {'id': '43-4041',
                        'name': 'Credit Authorizers, Checkers, and Clerks'},
                       {'id': '43-4051',
                        'name': 'Customer Service Representatives'},
                       {'id': '43-9021', 'name': 'Data Entry Keyers'},
                       {'id': '43-9031', 'name': 'Desktop Publishers'},
                       {'id': '43-5032',
                        'name': 'Dispatchers, Except Police, Fire, and Ambulance'},
                       {'id': '43-4061',
                        'name': 'Eligibility Interviewers, Government Programs'},
                       {'id': '43-6011',
                        'name': 'Executive Secretaries and Executive Administrative Assistants'},
                       {'id': '43-4071', 'name': 'File Clerks'},
                       {'id': '43-1011',
                        'name': 'First-Line Supervisors of Office and Administrative Support Workers'},
                       {'id': '43-3041', 'name': 'Gaming Cage Workers'},
                       {'id': '43-4081',
                        'name': 'Hotel, Motel, and Resort Desk Clerks'},
                       {'id': '43-4161',
                        'name': 'Human Resources Assistants, Except Payroll and Timekeeping'},
                       {'id': '43-4199',
                        'name': 'Information and Record Clerks, All Other'},
                       {'id': '43-9041',
                        'name': 'Insurance Claims and Policy Processing Clerks'},
                       {'id': '43-4111',
                        'name': 'Interviewers, Except Eligibility and Loan'},
                       {'id': '43-6012', 'name': 'Legal Secretaries'},
                       {'id': '43-4121',
                        'name': 'Library Assistants, Clerical'},
                       {'id': '43-4131',
                        'name': 'Loan Interviewers and Clerks'},
                       {'id': '43-9051',
                        'name': 'Mail Clerks and Mail Machine Operators, Except Postal Service'},
                       {'id': '43-6013', 'name': 'Medical Secretaries'},
                       {'id': '43-5041', 'name': 'Meter Readers, Utilities'},
                       {'id': '43-4141', 'name': 'New Accounts Clerks'},
                       {'id': '43-9799',
                        'name': 'Office and Administrative Support Workers, All Other*'},
                       {'id': '43-9061', 'name': 'Office Clerks, General'},
                       {'id': '43-9071',
                        'name': 'Office Machine Operators, Except Computer'},
                       {'id': '43-4151', 'name': 'Order Clerks'},
                       {'id': '43-3051',
                        'name': 'Payroll and Timekeeping Clerks'},
                       {'id': '43-5031',
                        'name': 'Police, Fire, and Ambulance Dispatchers'},
                       {'id': '43-5051', 'name': 'Postal Service Clerks'},
                       {'id': '43-5052',
                        'name': 'Postal Service Mail Carriers'},
                       {'id': '43-5053',
                        'name': 'Postal Service Mail Sorters, Processors, and Processing Machine Operators'},
                       {'id': '43-3061', 'name': 'Procurement Clerks'},
                       {'id': '43-5061',
                        'name': 'Production, Planning, and Expediting Clerks'},
                       {'id': '43-9081',
                        'name': 'Proofreaders and Copy Markers'},
                       {'id': '43-4171',
                        'name': 'Receptionists and Information Clerks'},
                       {'id': '43-4181',
                        'name': 'Reservation and Transportation Ticket Agents and Travel Clerks'},
                       {'id': '43-6014',
                        'name': 'Secretaries and Administrative Assistants, Except Legal, Medical, and Executive'},
                       {'id': '43-5071',
                        'name': 'Shipping, Receiving, and Traffic Clerks'},
                       {'id': '43-9111', 'name': 'Statistical Assistants'},
                       {'id': '43-5081',
                        'name': 'Stock Clerks and Order Fillers'},
                       {'id': '43-2011',
                        'name': 'Switchboard Operators, Including Answering Service'},
                       {'id': '43-2021', 'name': 'Telephone Operators'},
                       {'id': '43-3071', 'name': 'Tellers'},
                       {'id': '43-5111',
                        'name': 'Weighers, Measurers, Checkers, and Samplers, Recordkeeping'},
                       {'id': '43-9022',
                        'name': 'Word Processors and Typists'}]},
 45L: {'name': 'Farming, Fishing, and Forestry',
       'occupations': [{'id': '45-2091',
                        'name': 'Agricultural Equipment Operators'},
                       {'id': '45-2011', 'name': 'Agricultural Inspectors'},
                       {'id': '45-2099',
                        'name': 'Agricultural Workers, All Other'},
                       {'id': '45-2021', 'name': 'Animal Breeders'},
                       {'id': '45-4021', 'name': 'Fallers'},
                       {'id': '45-2092',
                        'name': 'Farmworkers and Laborers, Crop, Nursery, and Greenhouse'},
                       {'id': '45-2093',
                        'name': 'Farmworkers, Farm, Ranch, and Aquacultural Animals'},
                       {'id': '45-1011',
                        'name': 'First-Line Supervisors of Farming, Fishing, and Forestry Workers'},
                       {'id': '45-3011',
                        'name': 'Fishers and Related Fishing Workers'},
                       {'id': '45-4011',
                        'name': 'Forest and Conservation Workers'},
                       {'id': '45-2041',
                        'name': 'Graders and Sorters, Agricultural Products'},
                       {'id': '45-4023', 'name': 'Log Graders and Scalers'},
                       {'id': '45-4022',
                        'name': 'Logging Equipment Operators'},
                       {'id': '45-4029',
                        'name': 'Logging Workers, All Other'}]},
 47L: {'name': 'Construction and Extraction',
       'occupations': [{'id': '47-2011', 'name': 'Boilermakers'},
                       {'id': '47-2021',
                        'name': 'Brickmasons and Blockmasons'},
                       {'id': '47-2031', 'name': 'Carpenters'},
                       {'id': '47-2041', 'name': 'Carpet Installers'},
                       {'id': '47-2051',
                        'name': 'Cement Masons and Concrete Finishers'},
                       {'id': '47-4011',
                        'name': 'Construction and Building Inspectors'},
                       {'id': '47-4799',
                        'name': 'Construction and Related Workers, All Other*'},
                       {'id': '47-2061', 'name': 'Construction Laborers'},
                       {'id': '47-5041',
                        'name': 'Continuous Mining Machine Operators'},
                       {'id': '47-5011',
                        'name': 'Derrick Operators, Oil and Gas'},
                       {'id': '47-2081',
                        'name': 'Drywall and Ceiling Tile Installers'},
                       {'id': '47-5021',
                        'name': 'Earth Drillers, Except Oil and Gas'},
                       {'id': '47-2111', 'name': 'Electricians'},
                       {'id': '47-4021',
                        'name': 'Elevator Installers and Repairers'},
                       {'id': '47-5031',
                        'name': 'Explosives Workers, Ordnance Handling Experts, and Blasters'},
                       {'id': '47-5099',
                        'name': 'Extraction Workers, All Other'},
                       {'id': '47-4031', 'name': 'Fence Erectors'},
                       {'id': '47-1011',
                        'name': 'First-Line Supervisors of Construction Trades and Extraction Workers'},
                       {'id': '47-2042',
                        'name': 'Floor Layers, Except Carpet, Wood, and Hard Tiles'},
                       {'id': '47-2043',
                        'name': 'Floor Sanders and Finishers'},
                       {'id': '47-2121', 'name': 'Glaziers'},
                       {'id': '47-4041',
                        'name': 'Hazardous Materials Removal Workers'},
                       {'id': '47-3019',
                        'name': 'Helpers, Construction Trades, All Other'},
                       {'id': '47-3011',
                        'name': 'Helpers--Brickmasons, Blockmasons, Stonemasons, and Tile and Marble Setters'},
                       {'id': '47-3012', 'name': 'Helpers--Carpenters'},
                       {'id': '47-3013', 'name': 'Helpers--Electricians'},
                       {'id': '47-5081',
                        'name': 'Helpers--Extraction Workers'},
                       {'id': '47-3014',
                        'name': 'Helpers--Painters, Paperhangers, Plasterers, and Stucco Masons'},
                       {'id': '47-3015',
                        'name': 'Helpers--Pipelayers, Plumbers, Pipefitters, and Steamfitters'},
                       {'id': '47-3016', 'name': 'Helpers--Roofers'},
                       {'id': '47-4051',
                        'name': 'Highway Maintenance Workers'},
                       {'id': '47-2131',
                        'name': 'Insulation Workers, Floor, Ceiling, and Wall'},
                       {'id': '47-2132',
                        'name': 'Insulation Workers, Mechanical'},
                       {'id': '47-5042',
                        'name': 'Mine Cutting and Channeling Machine Operators'},
                       {'id': '47-5049',
                        'name': 'Mining Machine Operators, All Other'},
                       {'id': '47-2073',
                        'name': 'Operating Engineers and Other Construction Equipment Operators'},
                       {'id': '47-2141',
                        'name': 'Painters, Construction and Maintenance'},
                       {'id': '47-2142', 'name': 'Paperhangers'},
                       {'id': '47-2071',
                        'name': 'Paving, Surfacing, and Tamping Equipment Operators'},
                       {'id': '47-2072', 'name': 'Pile-Driver Operators'},
                       {'id': '47-2151', 'name': 'Pipelayers'},
                       {'id': '47-2161',
                        'name': 'Plasterers and Stucco Masons'},
                       {'id': '47-2152',
                        'name': 'Plumbers, Pipefitters, and Steamfitters'},
                       {'id': '47-4061',
                        'name': 'Rail-Track Laying and Maintenance Equipment Operators'},
                       {'id': '47-2171',
                        'name': 'Reinforcing Iron and Rebar Workers'},
                       {'id': '47-5051', 'name': 'Rock Splitters, Quarry'},
                       {'id': '47-5061', 'name': 'Roof Bolters, Mining'},
                       {'id': '47-2181', 'name': 'Roofers'},
                       {'id': '47-5012',
                        'name': 'Rotary Drill Operators, Oil and Gas'},
                       {'id': '47-5071', 'name': 'Roustabouts, Oil and Gas'},
                       {'id': '47-4071',
                        'name': 'Septic Tank Servicers and Sewer Pipe Cleaners'},
                       {'id': '47-5013',
                        'name': 'Service Unit Operators, Oil, Gas, and Mining'},
                       {'id': '47-2211', 'name': 'Sheet Metal Workers'},
                       {'id': '47-2022', 'name': 'Stonemasons'},
                       {'id': '47-2221',
                        'name': 'Structural Iron and Steel Workers'},
                       {'id': '47-2082', 'name': 'Tapers'},
                       {'id': '47-2053',
                        'name': 'Terrazzo Workers and Finishers'},
                       {'id': '47-2044', 'name': 'Tile and Marble Setters'}]},
 49L: {'name': 'Installation, Maintenance, and Repair',
       'occupations': [{'id': '49-3011',
                        'name': 'Aircraft Mechanics and Service Technicians'},
                       {'id': '49-3021',
                        'name': 'Automotive Body and Related Repairers'},
                       {'id': '49-3022',
                        'name': 'Automotive Glass Installers and Repairers'},
                       {'id': '49-3023',
                        'name': 'Automotive Service Technicians and Mechanics'},
                       {'id': '49-2091', 'name': 'Avionics Technicians'},
                       {'id': '49-3091', 'name': 'Bicycle Repairers'},
                       {'id': '49-3031',
                        'name': 'Bus and Truck Mechanics and Diesel Engine Specialists'},
                       {'id': '49-9061',
                        'name': 'Camera and Photographic Equipment Repairers'},
                       {'id': '49-9091',
                        'name': 'Coin, Vending, and Amusement Machine Servicers and Repairers'},
                       {'id': '49-9092', 'name': 'Commercial Divers'},
                       {'id': '49-2011',
                        'name': 'Computer, Automated Teller, and Office Machine Repairers'},
                       {'id': '49-9012',
                        'name': 'Control and Valve Installers and Repairers, Except Mechanical Door'},
                       {'id': '49-2092',
                        'name': 'Electric Motor, Power Tool, and Related Repairers'},
                       {'id': '49-2093',
                        'name': 'Electrical and Electronics Installers and Repairers, Transportation Equipment'},
                       {'id': '49-2094',
                        'name': 'Electrical and Electronics Repairers, Commercial and Industrial Equipment'},
                       {'id': '49-2095',
                        'name': 'Electrical and Electronics Repairers, Powerhouse, Substation, and Relay'},
                       {'id': '49-9051',
                        'name': 'Electrical Power-Line Installers and Repairers'},
                       {'id': '49-2096',
                        'name': 'Electronic Equipment Installers and Repairers, Motor Vehicles'},
                       {'id': '49-2097',
                        'name': 'Electronic Home Entertainment Equipment Installers and Repairers'},
                       {'id': '49-9093',
                        'name': 'Fabric Menders, Except Garment'},
                       {'id': '49-3041',
                        'name': 'Farm Equipment Mechanics and Service Technicians'},
                       {'id': '49-1011',
                        'name': 'First-Line Supervisors of Mechanics, Installers, and Repairers'},
                       {'id': '49-9021',
                        'name': 'Heating, Air Conditioning, and Refrigeration Mechanics and Installers'},
                       {'id': '49-9098',
                        'name': 'Helpers--Installation, Maintenance, and Repair Workers'},
                       {'id': '49-9031', 'name': 'Home Appliance Repairers'},
                       {'id': '49-9041',
                        'name': 'Industrial Machinery Mechanics'},
                       {'id': '49-9799',
                        'name': 'Installation, Maintenance, and Repair Workers, All Other*'},
                       {'id': '49-9094',
                        'name': 'Locksmiths and Safe Repairers'},
                       {'id': '49-9071',
                        'name': 'Maintenance and Repair Workers, General'},
                       {'id': '49-9043',
                        'name': 'Maintenance Workers, Machinery'},
                       {'id': '49-9095',
                        'name': 'Manufactured Building and Mobile Home Installers'},
                       {'id': '49-9011',
                        'name': 'Mechanical Door Repairers'},
                       {'id': '49-9062',
                        'name': 'Medical Equipment Repairers'},
                       {'id': '49-9044', 'name': 'Millwrights'},
                       {'id': '49-3042',
                        'name': 'Mobile Heavy Equipment Mechanics, Except Engines'},
                       {'id': '49-3051',
                        'name': 'Motorboat Mechanics and Service Technicians'},
                       {'id': '49-3052', 'name': 'Motorcycle Mechanics'},
                       {'id': '49-9063',
                        'name': 'Musical Instrument Repairers and Tuners'},
                       {'id': '49-3053',
                        'name': 'Outdoor Power Equipment and Other Small Engine Mechanics'},
                       {'id': '49-9069',
                        'name': 'Precision Instrument and Equipment Repairers, All Other'},
                       {'id': '49-2021',
                        'name': 'Radio, Cellular, and Tower Equipment Installers and Repairs'},
                       {'id': '49-3043', 'name': 'Rail Car Repairers'},
                       {'id': '49-3092',
                        'name': 'Recreational Vehicle Service Technicians'},
                       {'id': '49-9045',
                        'name': 'Refractory Materials Repairers, Except Brickmasons'},
                       {'id': '49-9096', 'name': 'Riggers'},
                       {'id': '49-2098',
                        'name': 'Security and Fire Alarm Systems Installers'},
                       {'id': '49-9097',
                        'name': 'Signal and Track Switch Repairers'},
                       {'id': '49-2022',
                        'name': 'Telecommunications Equipment Installers and Repairers, Except Line Installers'},
                       {'id': '49-9052',
                        'name': 'Telecommunications Line Installers and Repairers'},
                       {'id': '49-3093',
                        'name': 'Tire Repairers and Changers'},
                       {'id': '49-9064', 'name': 'Watch Repairers'}]},
 51L: {'name': 'Production',
       'occupations': [{'id': '51-9191',
                        'name': 'Adhesive Bonding Machine Operators and Tenders'},
                       {'id': '51-2011',
                        'name': 'Aircraft Structure, Surfaces, Rigging, and Systems Assemblers'},
                       {'id': '51-2099',
                        'name': 'Assemblers and Fabricators, All Other'},
                       {'id': '51-3011', 'name': 'Bakers'},
                       {'id': '51-3021',
                        'name': 'Butchers and Meat Cutters'},
                       {'id': '51-7011',
                        'name': 'Cabinetmakers and Bench Carpenters'},
                       {'id': '51-9011',
                        'name': 'Chemical Equipment Operators and Tenders'},
                       {'id': '51-8091',
                        'name': 'Chemical Plant and System Operators'},
                       {'id': '51-9192',
                        'name': 'Cleaning, Washing, and Metal Pickling Equipment Operators and Tenders'},
                       {'id': '51-9121',
                        'name': 'Coating, Painting, and Spraying Machine Setters, Operators, and Tenders'},
                       {'id': '51-2021',
                        'name': 'Coil Winders, Tapers, and Finishers'},
                       {'id': '51-4012',
                        'name': 'Computer Numerically Controlled Machine Tool Programmers, Metal and Plastic'},
                       {'id': '51-4011',
                        'name': 'Computer-Controlled Machine Tool Operators, Metal and Plastic'},
                       {'id': '51-9193',
                        'name': 'Cooling and Freezing Equipment Operators and Tenders'},
                       {'id': '51-9021',
                        'name': 'Crushing, Grinding, and Polishing Machine Setters, Operators, and Tenders'},
                       {'id': '51-9031',
                        'name': 'Cutters and Trimmers, Hand'},
                       {'id': '51-9032',
                        'name': 'Cutting and Slicing Machine Setters, Operators, and Tenders'},
                       {'id': '51-4031',
                        'name': 'Cutting, Punching, and Press Machine Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-9081',
                        'name': 'Dental Laboratory Technicians'},
                       {'id': '51-4032',
                        'name': 'Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-2022',
                        'name': 'Electrical and Electronic Equipment Assemblers'},
                       {'id': '51-2023',
                        'name': 'Electromechanical Equipment Assemblers'},
                       {'id': '51-2031',
                        'name': 'Engine and Other Machine Assemblers'},
                       {'id': '51-9194', 'name': 'Etchers and Engravers'},
                       {'id': '51-4021',
                        'name': 'Extruding and Drawing Machine Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-6091',
                        'name': 'Extruding and Forming Machine Setters, Operators, and Tenders, Synthetic and Glass Fibers'},
                       {'id': '51-9041',
                        'name': 'Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders'},
                       {'id': '51-6092',
                        'name': 'Fabric and Apparel Patternmakers'},
                       {'id': '51-2091',
                        'name': 'Fiberglass Laminators and Fabricators'},
                       {'id': '51-1011',
                        'name': 'First-Line Supervisors of Production and Operating Workers'},
                       {'id': '51-3091',
                        'name': 'Food and Tobacco Roasting, Baking, and Drying Machine Operators and Tenders'},
                       {'id': '51-3092', 'name': 'Food Batchmakers'},
                       {'id': '51-3093',
                        'name': 'Food Cooking Machine Operators and Tenders'},
                       {'id': '51-4022',
                        'name': 'Forging Machine Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-4071',
                        'name': 'Foundry Mold and Coremakers'},
                       {'id': '51-9051',
                        'name': 'Furnace, Kiln, Oven, Drier, and Kettle Operators and Tenders'},
                       {'id': '51-7021', 'name': 'Furniture Finishers'},
                       {'id': '51-8092', 'name': 'Gas Plant Operators'},
                       {'id': '51-9022',
                        'name': 'Grinding and Polishing Workers, Hand'},
                       {'id': '51-4033',
                        'name': 'Grinding, Lapping, Polishing, and Buffing Machine Tool Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-4191',
                        'name': 'Heat Treating Equipment Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-9198',
                        'name': 'Helpers--Production Workers'},
                       {'id': '51-9061',
                        'name': 'Inspectors, Testers, Sorters, Samplers, and Weighers'},
                       {'id': '51-9071',
                        'name': 'Jewelers and Precious Stone and Metal Workers'},
                       {'id': '51-4034',
                        'name': 'Lathe and Turning Machine Tool Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-6011',
                        'name': 'Laundry and Dry-Cleaning Workers'},
                       {'id': '51-4192',
                        'name': 'Layout Workers, Metal and Plastic'},
                       {'id': '51-4041', 'name': 'Machinists'},
                       {'id': '51-3022',
                        'name': 'Meat, Poultry, and Fish Cutters and Trimmers'},
                       {'id': '51-9082',
                        'name': 'Medical Appliance Technicians'},
                       {'id': '51-4199',
                        'name': 'Metal Workers and Plastic Workers, All Other'},
                       {'id': '51-4051',
                        'name': 'Metal-Refining Furnace Operators and Tenders'},
                       {'id': '51-4035',
                        'name': 'Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-9023',
                        'name': 'Mixing and Blending Machine Setters, Operators, and Tenders'},
                       {'id': '51-4061',
                        'name': 'Model Makers, Metal and Plastic'},
                       {'id': '51-7031', 'name': 'Model Makers, Wood'},
                       {'id': '51-9195',
                        'name': 'Molders, Shapers, and Casters, Except Metal and Plastic'},
                       {'id': '51-4072',
                        'name': 'Molding, Coremaking, and Casting Machine Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-4081',
                        'name': 'Multiple Machine Tool Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-8011',
                        'name': 'Nuclear Power Reactor Operators'},
                       {'id': '51-9083',
                        'name': 'Ophthalmic Laboratory Technicians'},
                       {'id': '51-9111',
                        'name': 'Packaging and Filling Machine Operators and Tenders'},
                       {'id': '51-9122',
                        'name': 'Painters, Transportation Equipment'},
                       {'id': '51-9123',
                        'name': 'Painting, Coating, and Decorating Workers'},
                       {'id': '51-9196',
                        'name': 'Paper Goods Machine Setters, Operators, and Tenders'},
                       {'id': '51-4062',
                        'name': 'Patternmakers, Metal and Plastic'},
                       {'id': '51-7032', 'name': 'Patternmakers, Wood'},
                       {'id': '51-8093',
                        'name': 'Petroleum Pump System Operators, Refinery Operators, and Gaugers'},
                       {'id': '51-9151',
                        'name': 'Photographic Process Workers and Processing Machine Operators'},
                       {'id': '51-8099',
                        'name': 'Plant and System Operators, All Other'},
                       {'id': '51-4193',
                        'name': 'Plating and Coating Machine Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-4052',
                        'name': 'Pourers and Casters, Metal'},
                       {'id': '51-8012',
                        'name': 'Power Distributors and Dispatchers'},
                       {'id': '51-8013', 'name': 'Power Plant Operators'},
                       {'id': '51-5111',
                        'name': 'Prepress Technicians and Workers'},
                       {'id': '51-6021',
                        'name': 'Pressers, Textile, Garment, and Related Materials'},
                       {'id': '51-5113',
                        'name': 'Print Binding and Finishing Workers'},
                       {'id': '51-5112', 'name': 'Printing Press Operators'},
                       {'id': '51-9399',
                        'name': 'Production Workers, All Other*'},
                       {'id': '51-4023',
                        'name': 'Rolling Machine Setters, Operators, and Tenders, Metal and Plastic'},
                       {'id': '51-7041',
                        'name': 'Sawing Machine Setters, Operators, and Tenders, Wood'},
                       {'id': '51-9141', 'name': 'Semiconductor Processors'},
                       {'id': '51-9012',
                        'name': 'Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders'},
                       {'id': '51-6051', 'name': 'Sewers, Hand'},
                       {'id': '51-6031', 'name': 'Sewing Machine Operators'},
                       {'id': '51-6041',
                        'name': 'Shoe and Leather Workers and Repairers'},
                       {'id': '51-6042',
                        'name': 'Shoe Machine Operators and Tenders'},
                       {'id': '51-3023',
                        'name': 'Slaughterers and Meat Packers'},
                       {'id': '51-8021',
                        'name': 'Stationary Engineers and Boiler Operators'},
                       {'id': '51-2041',
                        'name': 'Structural Metal Fabricators and Fitters'},
                       {'id': '51-6052',
                        'name': 'Tailors, Dressmakers, and Custom Sewers'},
                       {'id': '51-2092', 'name': 'Team Assemblers'},
                       {'id': '51-6061',
                        'name': 'Textile Bleaching and Dyeing Machine Operators and Tenders'},
                       {'id': '51-6062',
                        'name': 'Textile Cutting Machine Setters, Operators, and Tenders'},
                       {'id': '51-6063',
                        'name': 'Textile Knitting and Weaving Machine Setters, Operators, and Tenders'},
                       {'id': '51-6064',
                        'name': 'Textile Winding, Twisting, and Drawing Out Machine Setters, Operators, and Tenders'},
                       {'id': '51-6099',
                        'name': 'Textile, Apparel, and Furnishings Workers, All Other'},
                       {'id': '51-2093',
                        'name': 'Timing Device Assemblers and Adjusters'},
                       {'id': '51-9197', 'name': 'Tire Builders'},
                       {'id': '51-4111', 'name': 'Tool and Die Makers'},
                       {'id': '51-4194',
                        'name': 'Tool Grinders, Filers, and Sharpeners'},
                       {'id': '51-6093', 'name': 'Upholsterers'},
                       {'id': '51-8031',
                        'name': 'Water and Wastewater Treatment Plant and System Operators'},
                       {'id': '51-4121',
                        'name': 'Welders, Cutters, Solderers, and Brazers'},
                       {'id': '51-4122',
                        'name': 'Welding, Soldering, and Brazing Machine Setters, Operators, and Tenders'},
                       {'id': '51-7099', 'name': 'Woodworkers, All Other'},
                       {'id': '51-7042',
                        'name': 'Woodworking Machine Setters, Operators, and Tenders, Except Sawing'}]},
 53L: {'name': 'Transportation and Material Moving',
       'occupations': [{'id': '53-2021', 'name': 'Air Traffic Controllers'},
                       {'id': '53-1011',
                        'name': 'Aircraft Cargo Handling Supervisors'},
                       {'id': '53-2022',
                        'name': 'Airfield Operations Specialists'},
                       {'id': '53-2011',
                        'name': 'Airline Pilots, Copilots, and Flight Engineers'},
                       {'id': '53-3011',
                        'name': 'Ambulance Drivers and Attendants, Except Emergency Medical Technicians'},
                       {'id': '53-6031',
                        'name': 'Automotive and Watercraft Service Attendants'},
                       {'id': '53-6011', 'name': 'Bridge and Lock Tenders'},
                       {'id': '53-3022',
                        'name': 'Bus Drivers, School or Special Client'},
                       {'id': '53-3021',
                        'name': 'Bus Drivers, Transit and Intercity'},
                       {'id': '53-5021',
                        'name': 'Captains, Mates, and Pilots of Water Vessels'},
                       {'id': '53-7061',
                        'name': 'Cleaners of Vehicles and Equipment'},
                       {'id': '53-2012', 'name': 'Commercial Pilots'},
                       {'id': '53-7011',
                        'name': 'Conveyor Operators and Tenders'},
                       {'id': '53-7021',
                        'name': 'Crane and Tower Operators'},
                       {'id': '53-7031', 'name': 'Dredge Operators'},
                       {'id': '53-3031', 'name': 'Driver/Sales Workers'},
                       {'id': '53-7032',
                        'name': 'Excavating and Loading Machine and Dragline Operators'},
                       {'id': '53-1021',
                        'name': 'First-Line Supervisors of Helpers, Laborers, and Material Movers, Hand'},
                       {'id': '53-1031',
                        'name': 'First-Line Supervisors of Transportation and Material-Moving Machine and Vehicle Operators'},
                       {'id': '53-2031', 'name': 'Flight Attendants'},
                       {'id': '53-7071',
                        'name': 'Gas Compressor and Gas Pumping Station Operators'},
                       {'id': '53-3032',
                        'name': 'Heavy and Tractor-Trailer Truck Drivers'},
                       {'id': '53-7041',
                        'name': 'Hoist and Winch Operators'},
                       {'id': '53-7051',
                        'name': 'Industrial Truck and Tractor Operators'},
                       {'id': '53-7062',
                        'name': 'Laborers and Freight, Stock, and Material Movers, Hand'},
                       {'id': '53-3033',
                        'name': 'Light Truck or Delivery Services Drivers'},
                       {'id': '53-7063',
                        'name': 'Machine Feeders and Offbearers'},
                       {'id': '53-7199',
                        'name': 'Material Moving Workers, All Other'},
                       {'id': '53-7111',
                        'name': 'Mine Shuttle Car Operators'},
                       {'id': '53-3099',
                        'name': 'Motor Vehicle Operators, All Other'},
                       {'id': '53-5022', 'name': 'Motorboat Operators'},
                       {'id': '53-7064',
                        'name': 'Packers and Packagers, Hand'},
                       {'id': '53-6021', 'name': 'Parking Lot Attendants'},
                       {'id': '53-7072',
                        'name': 'Pump Operators, Except Wellhead Pumpers'},
                       {'id': '53-4099',
                        'name': 'Rail Transportation Workers, All Other'},
                       {'id': '53-4013',
                        'name': 'Rail Yard Engineers, Dinkey Operators, and Hostlers'},
                       {'id': '53-4021',
                        'name': 'Railroad Brake, Signal, and Switch Operators'},
                       {'id': '53-4031',
                        'name': 'Railroad Conductors and Yardmasters'},
                       {'id': '53-7081',
                        'name': 'Refuse and Recyclable Material Collectors'},
                       {'id': '53-5011',
                        'name': 'Sailors and Marine Oilers'},
                       {'id': '53-5031', 'name': 'Ship Engineers'},
                       {'id': '53-7121',
                        'name': 'Tank Car, Truck, and Ship Loaders'},
                       {'id': '53-3041',
                        'name': 'Taxi Drivers and Chauffeurs'},
                       {'id': '53-6041', 'name': 'Traffic Technicians'},
                       {'id': '53-6061',
                        'name': 'Transportation Attendants, Except Flight Attendants'},
                       {'id': '53-6051',
                        'name': 'Transportation Inspectors'},
                       {'id': '53-6099',
                        'name': 'Transportation Workers, All Other'},
                       {'id': '53-7073', 'name': 'Wellhead Pumpers'}]}}
